export const CONVERSATION_TOPICS: Record<string, string[]> = {
  A1: [
    "Przedstawianie sie i pierwsze pytania",
    "Moja rodzina - kto jest kim",
    "Kolory wokol nas",
    "Liczby i ceny w sklepie",
    "Dni tygodnia i moj plan",
    "Pogoda dzisiaj",
    "Moje ulubione jedzenie",
    "Co lubie pic - kawa, herbata, woda",
    "Zwierzeta domowe",
    "Moj dom - pokoje i meble",
    "Ubrania - co dzisiaj nosisz",
    "Emocje - jak sie czujesz",
    "Proste zakupy w sklepie",
    "W kawiarni - zamawianie",
    "Godziny - ktora jest godzina",
    "Czesci ciala",
    "Proste kierunki - prawo, lewo, prosto",
    "Moje miasto - co tu jest",
    "Transport - autobus, tramwaj, samochod",
    "Pory roku i miesiace",
  ],
  A2: [
    "Moj typowy dzien od rana do wieczora",
    "Co robilem w weekend",
    "Moja droga do pracy lub szkoly",
    "Co robie kiedy pada deszcz",
    "Moja wieczorna rutyna przed snem",
    "Poranna rutyna - kawa czy herbata najpierw?",
    "Gotowanie vs zamawianie jedzenia",
    "Moja idealna kolacja urodzinowa",
    "Najpopularniejsze jedzenie w moim kraju",
    "Sniadanie w roznych krajach",
    "Ulubiony przepis - prosty opis",
    "Najlepsza podroz w moim zyciu",
    "Miasto vs wies - gdzie wole mieszkac",
    "Jak wyglada moja okolica",
    "Marzenie o podrozy - dokad i dlaczego",
    "Lotnisko i samolot - co robic",
    "Opisz kogos kogo podziwiasz",
    "Idealny wspolokator - jaki powinien byc",
    "Co robie ze znajomymi w weekend",
    "Jak poznaje nowych ludzi",
    "Moj najlepszy przyjaciel",
    "Moja wymarzona praca kiedy bylem dzieckiem",
    "Co lubie i nie lubie w swojej pracy",
    "Umiejetnosc ktora chce sie nauczyc w tym roku",
    "Jak wyobrazam sobie zycie za 5 lat",
    "Praca zdalna vs biuro",
    "W kawiarni - zamawianie i small talk",
    "Zgubiles sie - pytasz o droge",
    "Dzwonisz zeby odwolac wizyte u lekarza",
    "Reklamujesz produkt w sklepie",
    "Rezerwujesz stolik w restauracji",
    "Na poczcie - wysylasz paczke",
    "Koty vs psy - przekonaj mnie",
    "Najlepsza pora roku i dlaczego",
    "Rano vs wieczor - kiedy jestes najlepszy",
    "Najlepsza gra planszowa lub komputerowa",
    "Gdybym mial supermoce - co bym robil",
    "Moja ulubiona pora dnia i co wtedy robie",
    "Idealny dzien wolny - godzina po godzinie",
    "Najsmieszniejsza sytuacja jezykowa",
    "Co bym zabral na bezludna wyspe",
  ],
  B1: [
    "Podroze i wakacje - planowanie wyjazdu",
    "Praca i kariera - rozmowa kwalifikacyjna",
    "Zdrowie i sport - aktywnosc fizyczna",
    "Technologia w codziennym zyciu",
    "Ekologia i srodowisko - co moge zrobic",
    "Media spolecznosciowe - za i przeciw",
    "Edukacja - jak sie uczylem i jak sie ucze teraz",
    "Filmy i seriale - rekomendacje",
    "Muzyka - co slucham i dlaczego",
    "Kuchnia swiata - ulubione potrawy z roznych krajow",
    "Mieszkanie w obcym kraju - wyzwania i nagrody",
    "Wolontariat i pomaganie innym",
    "Moda i styl osobisty",
    "Historia mojego kraju - ciekawy fakt",
    "Roznice kulturowe w pracy",
    "Planowanie budzetu i oszczedzanie",
    "Relacje miedzypokoleniowe",
    "Zwyczaje swiateczne w roznych krajach",
    "Sport zimowy",
    "Jak technologia zmienia nasz jezyk",
    "Stereotypy o moim kraju - prawda czy falsz",
    "Zycie w duzym vs malym miescie",
    "Ksiazki ktore zmienily moje myslenie",
    "Tradycje i obyczaje ktore mnie zaskakuja",
    "Przyszlosc transportu",
  ],
  B2: [
    "Aktualne wydarzenia i ich wplyw",
    "Marzenia i ambitne plany na przyszlosc",
    "Sztuczna inteligencja - szanse i zagrozenia",
    "Work-life balance w roznych kulturach",
    "Etyka w biznesie",
    "Imigracja i integracja",
    "System edukacji - co bym zmienil",
    "Zmiany klimatyczne - lokalne perspektywy",
    "Przedsiebiorczosc - zalozenie wlasnej firmy",
    "Psychologia szczescia - co nas uszczeslliwia",
    "Model spoleczny nordycki",
    "Cyfrowy detoks - czy jest potrzebny",
    "Kultura pracy w Skandynawii vs reszta Europy",
    "Przyszlosc miast - jak beda wygladac za 50 lat",
    "Fenomen slow niemozliwych do przetlumaczenia",
    "Dlaczego jedne jezyki sa trudniejsze od innych",
    "Samotnosc w nowoczesnym swiecie",
    "Rola sztuki w spoleczenstwie",
    "Roznice miedzy pokoleniami w podejsciu do pracy",
    "Czy podroze naprawde ksztalca",
  ],
  C1: [
    "Filozofia zycia - co jest naprawde wazne",
    "Sztuka wspolczesna - geniusz czy szarlatanstwo",
    "Geopolityka nordycka",
    "Nauka i etyka - granice badan",
    "Globalizacja vs lokalna tozsamosc",
    "Demokracja w kryzysie",
    "Przyszlosc pracy w erze AI",
    "Wplyw mediow na opinie publiczna",
    "Sprawiedliwosc spoleczna i rownosc",
    "Nostalgia i idealizacja przeszlosci",
    "Czy mozna byc obiektywnym",
    "Fenomen populizmu w Europie",
    "Kultura cancel - wolnosc slowa vs odpowiedzialnosc",
    "Transhumanizm i przyszlosc czlowieka",
    "Rola panstwa w zyciu obywateli",
  ],
};
