export const WORLD_LANGUAGES = [
  { code: "pl", nameEn: "Polish", nameNative: "Polski", flag: "🇵🇱" },
  { code: "en", nameEn: "English", nameNative: "English", flag: "🇬🇧" },
  { code: "uk", nameEn: "Ukrainian", nameNative: "Українська", flag: "🇺🇦" },
  { code: "de", nameEn: "German", nameNative: "Deutsch", flag: "🇩🇪" },
  { code: "fr", nameEn: "French", nameNative: "Français", flag: "🇫🇷" },
  { code: "es", nameEn: "Spanish", nameNative: "Español", flag: "🇪🇸" },
  { code: "pt", nameEn: "Portuguese", nameNative: "Português", flag: "🇵🇹" },
  { code: "it", nameEn: "Italian", nameNative: "Italiano", flag: "🇮🇹" },
  { code: "nl", nameEn: "Dutch", nameNative: "Nederlands", flag: "🇳🇱" },
  { code: "sv", nameEn: "Swedish", nameNative: "Svenska", flag: "🇸🇪" },
  { code: "no", nameEn: "Norwegian", nameNative: "Norsk", flag: "🇳🇴" },
  { code: "da", nameEn: "Danish", nameNative: "Dansk", flag: "🇩🇰" },
  { code: "fi", nameEn: "Finnish", nameNative: "Suomi", flag: "🇫🇮" },
  { code: "ru", nameEn: "Russian", nameNative: "Русский", flag: "🇷🇺" },
  { code: "zh", nameEn: "Chinese", nameNative: "中文", flag: "🇨🇳" },
  { code: "ja", nameEn: "Japanese", nameNative: "日本語", flag: "🇯🇵" },
  { code: "ko", nameEn: "Korean", nameNative: "한국어", flag: "🇰🇷" },
  { code: "ar", nameEn: "Arabic", nameNative: "العربية", flag: "🇸🇦" },
  { code: "hi", nameEn: "Hindi", nameNative: "हिन्दी", flag: "🇮🇳" },
  { code: "tr", nameEn: "Turkish", nameNative: "Türkçe", flag: "🇹🇷" },
  { code: "ro", nameEn: "Romanian", nameNative: "Română", flag: "🇷🇴" },
  { code: "hu", nameEn: "Hungarian", nameNative: "Magyar", flag: "🇭🇺" },
  { code: "cs", nameEn: "Czech", nameNative: "Čeština", flag: "🇨🇿" },
  { code: "sk", nameEn: "Slovak", nameNative: "Slovenčina", flag: "🇸🇰" },
  { code: "bg", nameEn: "Bulgarian", nameNative: "Български", flag: "🇧🇬" },
  { code: "hr", nameEn: "Croatian", nameNative: "Hrvatski", flag: "🇭🇷" },
  { code: "sr", nameEn: "Serbian", nameNative: "Srpski", flag: "🇷🇸" },
  { code: "el", nameEn: "Greek", nameNative: "Ελληνικά", flag: "🇬🇷" },
  { code: "th", nameEn: "Thai", nameNative: "ภาษาไทย", flag: "🇹🇭" },
  { code: "vi", nameEn: "Vietnamese", nameNative: "Tiếng Việt", flag: "🇻🇳" },
  { code: "id", nameEn: "Indonesian", nameNative: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "ms", nameEn: "Malay", nameNative: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "tl", nameEn: "Filipino", nameNative: "Filipino", flag: "🇵🇭" },
  { code: "he", nameEn: "Hebrew", nameNative: "עברית", flag: "🇮🇱" },
  { code: "fa", nameEn: "Persian", nameNative: "فارسی", flag: "🇮🇷" },
  { code: "sw", nameEn: "Swahili", nameNative: "Kiswahili", flag: "🇰🇪" },
  { code: "lt", nameEn: "Lithuanian", nameNative: "Lietuvių", flag: "🇱🇹" },
  { code: "lv", nameEn: "Latvian", nameNative: "Latviešu", flag: "🇱🇻" },
  { code: "et", nameEn: "Estonian", nameNative: "Eesti", flag: "🇪🇪" },
  { code: "ka", nameEn: "Georgian", nameNative: "ქართული", flag: "🇬🇪" },
  { code: "hy", nameEn: "Armenian", nameNative: "Հայերեն", flag: "🇦🇲" },
  { code: "bn", nameEn: "Bengali", nameNative: "বাংলা", flag: "🇧🇩" },
  { code: "ta", nameEn: "Tamil", nameNative: "தமிழ்", flag: "🇱🇰" },
  { code: "ur", nameEn: "Urdu", nameNative: "اردو", flag: "🇵🇰" },
  { code: "sl", nameEn: "Slovenian", nameNative: "Slovenščina", flag: "🇸🇮" },
  { code: "mk", nameEn: "Macedonian", nameNative: "Македонски", flag: "🇲🇰" },
  { code: "sq", nameEn: "Albanian", nameNative: "Shqip", flag: "🇦🇱" },
  { code: "bs", nameEn: "Bosnian", nameNative: "Bosanski", flag: "🇧🇦" },
];
